import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Script from "next/script";
import Footer from "@/components/Footer";
import { RainbowkitConfig } from "@/config/RainbowkitConfig";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <RainbowkitConfig>
          <Header />
          {children}
          <Footer />
        </RainbowkitConfig>
      </body>
      <Script src="https://s3.tradingview.com/tv.js"></Script>
    </html>
  );
}
