name: telegram message

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            message: ${{ github.event.head_commit.message }}
            IDLE-AI/Frontend-IDLE
            changes: ${{ github.event.head_commit.url }}
            repository: ${{ github.repository }}
